# Generated by Django 4.2.4 on 2023-09-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_game', '0004_remove_game_game_id_alter_game_game_string_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
